name: Deploy to reindeer testing namespace

on:
  pull_request:
    types: [labeled]
  push:

jobs:
  log-response:
    name: log event
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{toJSON(github.event)}}"
  check-reindeer-test-ns-deployment:
    name: Check pull request label and commit message for reindeer testing namespace deployment
    runs-on: ubuntu-18.04
    if: contains(github.event.pull_request.labels.*.name, 'reindeer-testing-ns') || contains(github.event.commits.*.message,'[Instruct GHA] Deploy to reindeer test namespace')
    steps:
    - run: echo "Label 'reindeer-testing-ns' found in pull_request or '[Instruct GHA] Deploy to reindeer test namespace' found in commit message"

  Deploy-to-reindeer-namespace:
    runs-on: ubuntu-latest
    needs: ["check-reindeer-test-ns-deployment"]
    steps:
      - run: echo "Deploying is a go"