name: Commit message echo


on:
  pull_request:

jobs:
  pre_ci:
    name: Extract PR metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          # We need to fetch with a depth of 2 for pull_request so we can do HEAD^2
          fetch-depth: 2

        # If this workflow was triggered by a pull request (open or synchronize!) then resolve the commit message from HEAD^2
        # It is stored in output steps, to be referenced with ${{ steps.pr_get_commit_message.outputs.pr_commit_message }}
      - name: "[Pull Request] Get commit message"
        if: github.event_name == 'pull_request'
        id: pr_get_commit_message
        run: echo ::set-output name=pr_commit_message::$(git log --format=%B -n 1 HEAD^2)
       
      - name: "[Pull Request] Get branch Labels"
        if: github.event_name == 'pull_request'
        id: pr_get_labels
        run: echo ::set-output name=pr_labels::${{toJSON(github.event.pull_request.labels.*.name)}}

  
    # For **Pull Request** events this will resolve to something like "$( [ -z "commit message pr" ] && echo "" || echo "commit message pr" )" which then resolves to just "commit message pr"  
    outputs:
      pr_commit_message: $( [ -z "${{ steps.pr_get_commit_message.outputs.pr_commit_message }}" ] && echo "${{ steps.pr_get_commit_message.outputs.pr_commit_message }}" )
      pr_labels: ${{steps.pr_get_labels.outputs.pr_labels}}

  echo_pr_metadata:
    name: Echo PR Metadata
    runs-on: ubuntu-latest
    needs: pre_ci
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

        # If this job doesn't get skipped you'll see the commit message appear here, it's just a debugging this
        # so be sure to remove it for your actual workflow
      - name: Log PR commit message
        run: echo "${{ needs.pre_ci.outputs.pr_commit_message }}"
      - name: Log PR labels
        run: echo "${{ needs.pre_ci.outputs.pr_labels }}"

  # This job can be skipped by including [skip ci] in the commit message
  skippable_job:
    name: Skippable Job
    runs-on: ubuntu-latest 
    if: "contains(needs.pre_ci.pr_labels, 'reindeer-testing-ns') && contains(needs.pre_ci.outputs.pr_commit_message, '[Instruct GHA] Deploy to reindeer test namespace')"
    needs: pre_ci
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

        # If this job doesn't get skipped you'll see the commit message appear here, it's just a debugging this
        # so be sure to remove it for your actual workflow
      - name: Log commit message
        run: echo "${{ needs.pre_ci.outputs.pr_commit_message }}"



