name: GitHub Actions Demo
on: [push]
jobs:
  Commit-debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{toJson(github)}}"
          echo "${{toJson(github.event.commits)}}"
          echo "${{toJson(github.event.commits.*.message)}}"